# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\florm\Documents\Mate\VS\Practica2\interfaz_hanoi.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 584)
        MainWindow.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.postes_salida = QtWidgets.QComboBox(self.centralwidget)
        self.postes_salida.setGeometry(QtCore.QRect(160, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.postes_salida.setFont(font)
        self.postes_salida.setAutoFillBackground(False)
        self.postes_salida.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.postes_salida.setEditable(False)
        self.postes_salida.setObjectName("postes_salida")
        self.postes_salida.addItem("")
        self.postes_salida.addItem("")
        self.postes_salida.addItem("")
        self.postes_entrada = QtWidgets.QComboBox(self.centralwidget)
        self.postes_entrada.setGeometry(QtCore.QRect(350, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.postes_entrada.setFont(font)
        self.postes_entrada.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.postes_entrada.setObjectName("postes_entrada")
        self.postes_entrada.addItem("")
        self.postes_entrada.addItem("")
        self.postes_entrada.addItem("")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 20, 681, 431))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Poste1 = QtWidgets.QLabel(self.frame)
        self.Poste1.setGeometry(QtCore.QRect(90, 70, 55, 331))
        self.Poste1.setAutoFillBackground(False)
        self.Poste1.setStyleSheet("background-color: rgb(149, 255, 220);\n"
"selection-background-color: rgb(69, 208, 208);")
        self.Poste1.setFrameShape(QtWidgets.QFrame.Box)
        self.Poste1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Poste1.setMidLineWidth(2)
        self.Poste1.setText("")
        self.Poste1.setObjectName("Poste1")
        self.Poste2 = QtWidgets.QLabel(self.frame)
        self.Poste2.setGeometry(QtCore.QRect(310, 70, 55, 331))
        self.Poste2.setAutoFillBackground(False)
        self.Poste2.setStyleSheet("background-color: rgb(149, 255, 220);\n"
"")
        self.Poste2.setFrameShape(QtWidgets.QFrame.Box)
        self.Poste2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Poste2.setMidLineWidth(2)
        self.Poste2.setText("")
        self.Poste2.setObjectName("Poste2")
        self.Poste3 = QtWidgets.QLabel(self.frame)
        self.Poste3.setGeometry(QtCore.QRect(530, 70, 55, 331))
        self.Poste3.setAutoFillBackground(False)
        self.Poste3.setStyleSheet("background-color: rgb(149, 255, 220);")
        self.Poste3.setFrameShape(QtWidgets.QFrame.Box)
        self.Poste3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Poste3.setMidLineWidth(2)
        self.Poste3.setText("")
        self.Poste3.setObjectName("Poste3")
        self.disco8 = QtWidgets.QLabel(self.frame)
        self.disco8.setGeometry(QtCore.QRect(26, 370, 184, 31))
        self.disco8.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.disco8.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco8.setText("")
        self.disco8.setObjectName("disco8")
        self.disco7 = QtWidgets.QLabel(self.frame)
        self.disco7.setGeometry(QtCore.QRect(34, 340, 168, 31))
        self.disco7.setStyleSheet("background-color: rgb(255, 122, 5);")
        self.disco7.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco7.setText("")
        self.disco7.setObjectName("disco7")
        self.disco6 = QtWidgets.QLabel(self.frame)
        self.disco6.setGeometry(QtCore.QRect(42, 310, 152, 31))
        self.disco6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.disco6.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco6.setText("")
        self.disco6.setObjectName("disco6")
        self.disco5 = QtWidgets.QLabel(self.frame)
        self.disco5.setGeometry(QtCore.QRect(50, 280, 136, 31))
        self.disco5.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.disco5.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco5.setText("")
        self.disco5.setObjectName("disco5")
        self.disco4 = QtWidgets.QLabel(self.frame)
        self.disco4.setGeometry(QtCore.QRect(58, 250, 120, 31))
        self.disco4.setStyleSheet("background-color: rgb(0, 218, 0);")
        self.disco4.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco4.setText("")
        self.disco4.setObjectName("disco4")
        self.disco3 = QtWidgets.QLabel(self.frame)
        self.disco3.setGeometry(QtCore.QRect(66, 220, 104, 31))
        self.disco3.setStyleSheet("background-color: rgb(0, 145, 255);")
        self.disco3.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco3.setText("")
        self.disco3.setObjectName("disco3")
        self.disco2 = QtWidgets.QLabel(self.frame)
        self.disco2.setGeometry(QtCore.QRect(74, 190, 88, 31))
        self.disco2.setStyleSheet("background-color: rgb(159, 0, 170);")
        self.disco2.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco2.setText("")
        self.disco2.setObjectName("disco2")
        self.disco1 = QtWidgets.QLabel(self.frame)
        self.disco1.setGeometry(QtCore.QRect(82, 160, 72, 31))
        self.disco1.setStyleSheet("background-color: rgb(255, 3, 125);\n"
"selection-background-color: rgb(255, 149, 192);")
        self.disco1.setFrameShape(QtWidgets.QFrame.Panel)
        self.disco1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disco1.setText("")
        self.disco1.setObjectName("disco1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 460, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 450, 101, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boton_mover = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boton_mover.setFont(font)
        self.boton_mover.setObjectName("boton_mover")
        self.verticalLayout.addWidget(self.boton_mover)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 520, 261, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contador_jugadas = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.contador_jugadas.setFont(font)
        self.contador_jugadas.setObjectName("contador_jugadas")
        self.verticalLayout_2.addWidget(self.contador_jugadas)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(138, 430, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(356, 430, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(573, 430, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(664, 542, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.disco1.setBuddy(self.postes_entrada)

        self.retranslateUi(MainWindow)
        self.postes_salida.setCurrentIndex(1)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.postes_salida.setItemText(0, _translate("MainWindow", "Poste 1"))
        self.postes_salida.setItemText(1, _translate("MainWindow", "Poste 2"))
        self.postes_salida.setItemText(2, _translate("MainWindow", "Poste 3"))
        self.postes_entrada.setItemText(0, _translate("MainWindow", "Poste 1"))
        self.postes_entrada.setItemText(1, _translate("MainWindow", "Poste 2"))
        self.postes_entrada.setItemText(2, _translate("MainWindow", "Poste 3"))
        self.label.setText(_translate("MainWindow", "Seleccionar disco en:"))
        self.label_2.setText(_translate("MainWindow", "Mover a:"))
        self.boton_mover.setText(_translate("MainWindow", "Mover"))
        self.contador_jugadas.setText(_translate("MainWindow", "Jugadas realizadas:"))
        self.label_3.setText(_translate("MainWindow", "Poste 1"))
        self.label_4.setText(_translate("MainWindow", "Poste 2"))
        self.label_5.setText(_translate("MainWindow", "Poste 3"))
        self.pushButton.setText(_translate("MainWindow", "Terminar"))

