# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\florm\Documents\Mate\Progra\Proyecto\login.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(648, 406)
        self.splitter = QtWidgets.QSplitter(Login)
        self.splitter.setGeometry(QtCore.QRect(130, 160, 181, 181))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_usuario = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_usuario.setFont(font)
        self.label_usuario.setObjectName("label_usuario")
        self.texto_correo = QtWidgets.QLineEdit(self.splitter)
        self.texto_correo.setObjectName("texto_correo")
        self.label_password = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.texto_password = QtWidgets.QLineEdit(self.splitter)
        self.texto_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.texto_password.setObjectName("texto_password")
        self.boton_ingresar = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_ingresar.setFont(font)
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.mensaje = QtWidgets.QLabel(Login)
        self.mensaje.setGeometry(QtCore.QRect(100, 360, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.mensaje.setFont(font)
        self.mensaje.setObjectName("mensaje")
        self.logo = QtWidgets.QLabel(Login)
        self.logo.setGeometry(QtCore.QRect(80, 10, 111, 121))
        font = QtGui.QFont()
        font.setKerning(True)
        self.logo.setFont(font)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/imagen/Logo0.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.splitter_2 = QtWidgets.QSplitter(Login)
        self.splitter_2.setGeometry(QtCore.QRect(380, 190, 141, 111))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.boton_crear = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.boton_crear.setFont(font)
        self.boton_crear.setObjectName("boton_crear")
        self.olvidar = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.olvidar.setFont(font)
        self.olvidar.setObjectName("olvidar")
        self.boton_recuperar = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.boton_recuperar.setFont(font)
        self.boton_recuperar.setObjectName("boton_recuperar")
        self.splitter_3 = QtWidgets.QSplitter(Login)
        self.splitter_3.setGeometry(QtCore.QRect(210, 40, 391, 61))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.nombre = QtWidgets.QLabel(self.splitter_3)
        self.nombre.setStyleSheet("font: 75 20pt \"Century Gothic\";")
        self.nombre.setObjectName("nombre")
        self.carnet = QtWidgets.QLabel(self.splitter_3)
        self.carnet.setStyleSheet("font: 75 16pt \"Century Gothic\";")
        self.carnet.setObjectName("carnet")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Inicio"))
        self.label_usuario.setText(_translate("Login", "Usuario"))
        self.label_password.setText(_translate("Login", "Contraseña"))
        self.boton_ingresar.setText(_translate("Login", "Ingresar"))
        self.mensaje.setText(_translate("Login", "Para iniciar una sesión de invitado, use como usuario y contraseña  ECFM"))
        self.boton_crear.setText(_translate("Login", "Crear usuario"))
        self.olvidar.setText(_translate("Login", "Olvidaste tu contraseña"))
        self.boton_recuperar.setText(_translate("Login", "Recuperar contraseña"))
        self.nombre.setText(_translate("Login", "Flor de María Pérez Medina"))
        self.carnet.setText(_translate("Login", "201314574"))

import logo_rc
