# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\florm\Documents\Mate\Progra\Proyecto\ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 761, 581))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 931, 250))
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_opcion = QtWidgets.QLabel(self.frame)
        self.label_opcion.setGeometry(QtCore.QRect(50, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_opcion.setFont(font)
        self.label_opcion.setObjectName("label_opcion")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 589, 140))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_grandes = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_grandes.setFont(font)
        self.checkBox_grandes.setStyleSheet("selection-background-color: rgb(0, 255, 0);")
        self.checkBox_grandes.setObjectName("checkBox_grandes")
        self.verticalLayout.addWidget(self.checkBox_grandes)
        self.checkBox_mes = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_mes.setFont(font)
        self.checkBox_mes.setObjectName("checkBox_mes")
        self.verticalLayout.addWidget(self.checkBox_mes)
        self.checkBox_USAC = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_USAC.setFont(font)
        self.checkBox_USAC.setChecked(False)
        self.checkBox_USAC.setAutoRepeat(False)
        self.checkBox_USAC.setAutoExclusive(False)
        self.checkBox_USAC.setTristate(False)
        self.checkBox_USAC.setObjectName("checkBox_USAC")
        self.verticalLayout.addWidget(self.checkBox_USAC)
        self.checkBox_proveedores = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_proveedores.setFont(font)
        self.checkBox_proveedores.setObjectName("checkBox_proveedores")
        self.verticalLayout.addWidget(self.checkBox_proveedores)
        self.boton_visualizar = QtWidgets.QPushButton(self.frame)
        self.boton_visualizar.setGeometry(QtCore.QRect(580, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_visualizar.setFont(font)
        self.boton_visualizar.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_visualizar.setObjectName("boton_visualizar")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, 250, 761, 301))
        self.frame_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_agregar = QtWidgets.QLabel(self.frame_2)
        self.label_agregar.setGeometry(QtCore.QRect(30, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_agregar.setFont(font)
        self.label_agregar.setObjectName("label_agregar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 671, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(31)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_modalidad = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_modalidad.setFont(font)
        self.label_modalidad.setObjectName("label_modalidad")
        self.gridLayout.addWidget(self.label_modalidad, 4, 1, 1, 1)
        self.comboBox_padre = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.comboBox_padre.setFont(font)
        self.comboBox_padre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_padre.setObjectName("comboBox_padre")
        self.comboBox_padre.addItem("")
        self.comboBox_padre.addItem("")
        self.comboBox_padre.addItem("")
        self.gridLayout.addWidget(self.comboBox_padre, 1, 0, 1, 1)
        self.label_compradora = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_compradora.setFont(font)
        self.label_compradora.setObjectName("label_compradora")
        self.gridLayout.addWidget(self.label_compradora, 7, 0, 1, 1)
        self.label_entidad = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_entidad.setFont(font)
        self.label_entidad.setObjectName("label_entidad")
        self.gridLayout.addWidget(self.label_entidad, 4, 0, 1, 1)
        self.label_nit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nit.setFont(font)
        self.label_nit.setObjectName("label_nit")
        self.gridLayout.addWidget(self.label_nit, 7, 1, 1, 1)
        self.label_nog = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nog.setFont(font)
        self.label_nog.setObjectName("label_nog")
        self.gridLayout.addWidget(self.label_nog, 0, 1, 1, 1)
        self.label_adjudicacion = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_adjudicacion.setFont(font)
        self.label_adjudicacion.setObjectName("label_adjudicacion")
        self.gridLayout.addWidget(self.label_adjudicacion, 7, 2, 1, 1)
        self.texto_entidad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_entidad.setFont(font)
        self.texto_entidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_entidad.setObjectName("texto_entidad")
        self.gridLayout.addWidget(self.texto_entidad, 6, 0, 1, 1)
        self.label_publicacion = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_publicacion.setFont(font)
        self.label_publicacion.setObjectName("label_publicacion")
        self.gridLayout.addWidget(self.label_publicacion, 4, 2, 1, 1)
        self.texto_nit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nit.setFont(font)
        self.texto_nit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nit.setObjectName("texto_nit")
        self.gridLayout.addWidget(self.texto_nit, 8, 1, 1, 1)
        self.texto_modalidad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_modalidad.setFont(font)
        self.texto_modalidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_modalidad.setObjectName("texto_modalidad")
        self.gridLayout.addWidget(self.texto_modalidad, 6, 1, 1, 1)
        self.label_monto = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_monto.setFont(font)
        self.label_monto.setObjectName("label_monto")
        self.gridLayout.addWidget(self.label_monto, 0, 2, 1, 1)
        self.label_padre = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_padre.setFont(font)
        self.label_padre.setObjectName("label_padre")
        self.gridLayout.addWidget(self.label_padre, 0, 0, 1, 1)
        self.texto_compradora = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_compradora.setFont(font)
        self.texto_compradora.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_compradora.setObjectName("texto_compradora")
        self.gridLayout.addWidget(self.texto_compradora, 8, 0, 1, 1)
        self.texto_nog = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nog.setFont(font)
        self.texto_nog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nog.setObjectName("texto_nog")
        self.gridLayout.addWidget(self.texto_nog, 1, 1, 1, 1)
        self.texto_monto = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_monto.setFont(font)
        self.texto_monto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_monto.setObjectName("texto_monto")
        self.gridLayout.addWidget(self.texto_monto, 1, 2, 1, 1)
        self.fecha_publicacion = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_publicacion.setFont(font)
        self.fecha_publicacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_publicacion.setMaximumDate(QtCore.QDate(2016, 12, 31))
        self.fecha_publicacion.setMinimumDate(QtCore.QDate(2016, 1, 1))
        self.fecha_publicacion.setCalendarPopup(True)
        self.fecha_publicacion.setObjectName("fecha_publicacion")
        self.gridLayout.addWidget(self.fecha_publicacion, 6, 2, 1, 1)
        self.fecha_adjudicacion = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_adjudicacion.setFont(font)
        self.fecha_adjudicacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_adjudicacion.setMaximumDate(QtCore.QDate(2016, 12, 31))
        self.fecha_adjudicacion.setMinimumDate(QtCore.QDate(2016, 1, 1))
        self.fecha_adjudicacion.setCalendarPopup(True)
        self.fecha_adjudicacion.setObjectName("fecha_adjudicacion")
        self.gridLayout.addWidget(self.fecha_adjudicacion, 8, 2, 1, 1)
        self.boton_actualizar = QtWidgets.QPushButton(self.frame_2)
        self.boton_actualizar.setGeometry(QtCore.QRect(580, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_actualizar.setFont(font)
        self.boton_actualizar.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 931, 250))
        self.frame_3.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_opcion_2 = QtWidgets.QLabel(self.frame_3)
        self.label_opcion_2.setGeometry(QtCore.QRect(50, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_opcion_2.setFont(font)
        self.label_opcion_2.setObjectName("label_opcion_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 589, 140))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_grandes_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_grandes_2.setFont(font)
        self.checkBox_grandes_2.setStyleSheet("selection-background-color: rgb(0, 255, 0);")
        self.checkBox_grandes_2.setObjectName("checkBox_grandes_2")
        self.verticalLayout_3.addWidget(self.checkBox_grandes_2)
        self.checkBox_mes_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_mes_2.setFont(font)
        self.checkBox_mes_2.setObjectName("checkBox_mes_2")
        self.verticalLayout_3.addWidget(self.checkBox_mes_2)
        self.checkBox_USAC_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_USAC_2.setFont(font)
        self.checkBox_USAC_2.setChecked(False)
        self.checkBox_USAC_2.setAutoRepeat(False)
        self.checkBox_USAC_2.setAutoExclusive(False)
        self.checkBox_USAC_2.setTristate(False)
        self.checkBox_USAC_2.setObjectName("checkBox_USAC_2")
        self.verticalLayout_3.addWidget(self.checkBox_USAC_2)
        self.checkBox_proveedores_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_proveedores_2.setFont(font)
        self.checkBox_proveedores_2.setObjectName("checkBox_proveedores_2")
        self.verticalLayout_3.addWidget(self.checkBox_proveedores_2)
        self.boton_visualizar_2 = QtWidgets.QPushButton(self.frame_3)
        self.boton_visualizar_2.setGeometry(QtCore.QRect(580, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_visualizar_2.setFont(font)
        self.boton_visualizar_2.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_visualizar_2.setObjectName("boton_visualizar_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 250, 761, 301))
        self.frame_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_agregar_2 = QtWidgets.QLabel(self.frame_4)
        self.label_agregar_2.setGeometry(QtCore.QRect(30, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_agregar_2.setFont(font)
        self.label_agregar_2.setObjectName("label_agregar_2")
        self.boton_actualizar_2 = QtWidgets.QPushButton(self.frame_4)
        self.boton_actualizar_2.setGeometry(QtCore.QRect(580, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_actualizar_2.setFont(font)
        self.boton_actualizar_2.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_actualizar_2.setObjectName("boton_actualizar_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 40, 671, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(31)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_modalidad_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_modalidad_2.setFont(font)
        self.label_modalidad_2.setObjectName("label_modalidad_2")
        self.gridLayout_2.addWidget(self.label_modalidad_2, 4, 1, 1, 1)
        self.comboBox_padre_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_padre_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.comboBox_padre_2.setFont(font)
        self.comboBox_padre_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_padre_2.setObjectName("comboBox_padre_2")
        self.comboBox_padre_2.addItem("")
        self.comboBox_padre_2.addItem("")
        self.comboBox_padre_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_padre_2, 1, 0, 1, 1)
        self.label_compradora_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_compradora_2.setFont(font)
        self.label_compradora_2.setObjectName("label_compradora_2")
        self.gridLayout_2.addWidget(self.label_compradora_2, 7, 0, 1, 1)
        self.label_entidad_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_entidad_2.setFont(font)
        self.label_entidad_2.setObjectName("label_entidad_2")
        self.gridLayout_2.addWidget(self.label_entidad_2, 4, 0, 1, 1)
        self.label_nit_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nit_2.setFont(font)
        self.label_nit_2.setObjectName("label_nit_2")
        self.gridLayout_2.addWidget(self.label_nit_2, 7, 1, 1, 1)
        self.label_nog_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nog_2.setFont(font)
        self.label_nog_2.setObjectName("label_nog_2")
        self.gridLayout_2.addWidget(self.label_nog_2, 0, 1, 1, 1)
        self.label_adjudicacion_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_adjudicacion_2.setFont(font)
        self.label_adjudicacion_2.setObjectName("label_adjudicacion_2")
        self.gridLayout_2.addWidget(self.label_adjudicacion_2, 7, 2, 1, 1)
        self.texto_entidad_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_entidad_2.setFont(font)
        self.texto_entidad_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_entidad_2.setObjectName("texto_entidad_2")
        self.gridLayout_2.addWidget(self.texto_entidad_2, 6, 0, 1, 1)
        self.label_publicacion_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_publicacion_2.setFont(font)
        self.label_publicacion_2.setObjectName("label_publicacion_2")
        self.gridLayout_2.addWidget(self.label_publicacion_2, 4, 2, 1, 1)
        self.texto_nit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nit_2.setFont(font)
        self.texto_nit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nit_2.setObjectName("texto_nit_2")
        self.gridLayout_2.addWidget(self.texto_nit_2, 8, 1, 1, 1)
        self.texto_modalidad_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_modalidad_2.setFont(font)
        self.texto_modalidad_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_modalidad_2.setObjectName("texto_modalidad_2")
        self.gridLayout_2.addWidget(self.texto_modalidad_2, 6, 1, 1, 1)
        self.label_monto_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_monto_2.setFont(font)
        self.label_monto_2.setObjectName("label_monto_2")
        self.gridLayout_2.addWidget(self.label_monto_2, 0, 2, 1, 1)
        self.label_padre_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_padre_2.setFont(font)
        self.label_padre_2.setObjectName("label_padre_2")
        self.gridLayout_2.addWidget(self.label_padre_2, 0, 0, 1, 1)
        self.texto_compradora_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_compradora_2.setFont(font)
        self.texto_compradora_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_compradora_2.setObjectName("texto_compradora_2")
        self.gridLayout_2.addWidget(self.texto_compradora_2, 8, 0, 1, 1)
        self.texto_nog_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nog_2.setFont(font)
        self.texto_nog_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nog_2.setObjectName("texto_nog_2")
        self.gridLayout_2.addWidget(self.texto_nog_2, 1, 1, 1, 1)
        self.texto_monto_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_monto_2.setFont(font)
        self.texto_monto_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_monto_2.setObjectName("texto_monto_2")
        self.gridLayout_2.addWidget(self.texto_monto_2, 1, 2, 1, 1)
        self.fecha_publicacion_2 = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_publicacion_2.setFont(font)
        self.fecha_publicacion_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_publicacion_2.setMaximumDate(QtCore.QDate(2017, 12, 31))
        self.fecha_publicacion_2.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.fecha_publicacion_2.setCalendarPopup(True)
        self.fecha_publicacion_2.setObjectName("fecha_publicacion_2")
        self.gridLayout_2.addWidget(self.fecha_publicacion_2, 6, 2, 1, 1)
        self.fecha_adjudicacion_2 = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_adjudicacion_2.setFont(font)
        self.fecha_adjudicacion_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_adjudicacion_2.setMaximumDate(QtCore.QDate(2017, 1, 1))
        self.fecha_adjudicacion_2.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.fecha_adjudicacion_2.setCalendarPopup(True)
        self.fecha_adjudicacion_2.setObjectName("fecha_adjudicacion_2")
        self.gridLayout_2.addWidget(self.fecha_adjudicacion_2, 8, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 931, 250))
        self.frame_6.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_opcion_4 = QtWidgets.QLabel(self.frame_6)
        self.label_opcion_4.setGeometry(QtCore.QRect(50, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_opcion_4.setFont(font)
        self.label_opcion_4.setObjectName("label_opcion_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(40, 40, 589, 140))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_grandes_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_grandes_4.setFont(font)
        self.checkBox_grandes_4.setStyleSheet("selection-background-color: rgb(0, 255, 0);")
        self.checkBox_grandes_4.setObjectName("checkBox_grandes_4")
        self.verticalLayout_5.addWidget(self.checkBox_grandes_4)
        self.checkBox_mes_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_mes_4.setFont(font)
        self.checkBox_mes_4.setObjectName("checkBox_mes_4")
        self.verticalLayout_5.addWidget(self.checkBox_mes_4)
        self.checkBox_USAC_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_USAC_4.setFont(font)
        self.checkBox_USAC_4.setChecked(False)
        self.checkBox_USAC_4.setAutoRepeat(False)
        self.checkBox_USAC_4.setAutoExclusive(False)
        self.checkBox_USAC_4.setTristate(False)
        self.checkBox_USAC_4.setObjectName("checkBox_USAC_4")
        self.verticalLayout_5.addWidget(self.checkBox_USAC_4)
        self.checkBox_proveedores_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.checkBox_proveedores_3.setFont(font)
        self.checkBox_proveedores_3.setObjectName("checkBox_proveedores_3")
        self.verticalLayout_5.addWidget(self.checkBox_proveedores_3)
        self.boton_visualizar_4 = QtWidgets.QPushButton(self.frame_6)
        self.boton_visualizar_4.setGeometry(QtCore.QRect(580, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_visualizar_4.setFont(font)
        self.boton_visualizar_4.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_visualizar_4.setObjectName("boton_visualizar_4")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 250, 761, 301))
        self.frame_5.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_agregar_4 = QtWidgets.QLabel(self.frame_5)
        self.label_agregar_4.setGeometry(QtCore.QRect(30, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_agregar_4.setFont(font)
        self.label_agregar_4.setObjectName("label_agregar_4")
        self.boton_actualizar_4 = QtWidgets.QPushButton(self.frame_5)
        self.boton_actualizar_4.setGeometry(QtCore.QRect(580, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_actualizar_4.setFont(font)
        self.boton_actualizar_4.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_actualizar_4.setObjectName("boton_actualizar_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 40, 671, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setHorizontalSpacing(31)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_modalidad_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_modalidad_3.setFont(font)
        self.label_modalidad_3.setObjectName("label_modalidad_3")
        self.gridLayout_3.addWidget(self.label_modalidad_3, 4, 1, 1, 1)
        self.comboBox_padre_3 = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.comboBox_padre_3.setFont(font)
        self.comboBox_padre_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_padre_3.setObjectName("comboBox_padre_3")
        self.comboBox_padre_3.addItem("")
        self.comboBox_padre_3.addItem("")
        self.comboBox_padre_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_padre_3, 1, 0, 1, 1)
        self.label_compradora_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_compradora_3.setFont(font)
        self.label_compradora_3.setObjectName("label_compradora_3")
        self.gridLayout_3.addWidget(self.label_compradora_3, 7, 0, 1, 1)
        self.label_entidad_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_entidad_3.setFont(font)
        self.label_entidad_3.setObjectName("label_entidad_3")
        self.gridLayout_3.addWidget(self.label_entidad_3, 4, 0, 1, 1)
        self.label_nit_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nit_3.setFont(font)
        self.label_nit_3.setObjectName("label_nit_3")
        self.gridLayout_3.addWidget(self.label_nit_3, 7, 1, 1, 1)
        self.label_nog_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_nog_3.setFont(font)
        self.label_nog_3.setObjectName("label_nog_3")
        self.gridLayout_3.addWidget(self.label_nog_3, 0, 1, 1, 1)
        self.label_adjudicacion_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_adjudicacion_3.setFont(font)
        self.label_adjudicacion_3.setObjectName("label_adjudicacion_3")
        self.gridLayout_3.addWidget(self.label_adjudicacion_3, 7, 2, 1, 1)
        self.texto_entidad_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_entidad_3.setFont(font)
        self.texto_entidad_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_entidad_3.setObjectName("texto_entidad_3")
        self.gridLayout_3.addWidget(self.texto_entidad_3, 6, 0, 1, 1)
        self.label_publicacion_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_publicacion_3.setFont(font)
        self.label_publicacion_3.setObjectName("label_publicacion_3")
        self.gridLayout_3.addWidget(self.label_publicacion_3, 4, 2, 1, 1)
        self.texto_nit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nit_3.setFont(font)
        self.texto_nit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nit_3.setObjectName("texto_nit_3")
        self.gridLayout_3.addWidget(self.texto_nit_3, 8, 1, 1, 1)
        self.texto_modalidad_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_modalidad_3.setFont(font)
        self.texto_modalidad_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_modalidad_3.setObjectName("texto_modalidad_3")
        self.gridLayout_3.addWidget(self.texto_modalidad_3, 6, 1, 1, 1)
        self.label_monto_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_monto_3.setFont(font)
        self.label_monto_3.setObjectName("label_monto_3")
        self.gridLayout_3.addWidget(self.label_monto_3, 0, 2, 1, 1)
        self.label_padre_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_padre_3.setFont(font)
        self.label_padre_3.setObjectName("label_padre_3")
        self.gridLayout_3.addWidget(self.label_padre_3, 0, 0, 1, 1)
        self.texto_compradora_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_compradora_3.setFont(font)
        self.texto_compradora_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_compradora_3.setObjectName("texto_compradora_3")
        self.gridLayout_3.addWidget(self.texto_compradora_3, 8, 0, 1, 1)
        self.texto_nog_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_nog_3.setFont(font)
        self.texto_nog_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_nog_3.setObjectName("texto_nog_3")
        self.gridLayout_3.addWidget(self.texto_nog_3, 1, 1, 1, 1)
        self.texto_monto_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.texto_monto_3.setFont(font)
        self.texto_monto_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto_monto_3.setObjectName("texto_monto_3")
        self.gridLayout_3.addWidget(self.texto_monto_3, 1, 2, 1, 1)
        self.fecha_publicacion_3 = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_publicacion_3.setFont(font)
        self.fecha_publicacion_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_publicacion_3.setMaximumDate(QtCore.QDate(2018, 10, 31))
        self.fecha_publicacion_3.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.fecha_publicacion_3.setCalendarPopup(True)
        self.fecha_publicacion_3.setObjectName("fecha_publicacion_3")
        self.gridLayout_3.addWidget(self.fecha_publicacion_3, 6, 2, 1, 1)
        self.fecha_adjudicacion_3 = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.fecha_adjudicacion_3.setFont(font)
        self.fecha_adjudicacion_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_adjudicacion_3.setMaximumDate(QtCore.QDate(2018, 10, 31))
        self.fecha_adjudicacion_3.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.fecha_adjudicacion_3.setCalendarPopup(True)
        self.fecha_adjudicacion_3.setObjectName("fecha_adjudicacion_3")
        self.gridLayout_3.addWidget(self.fecha_adjudicacion_3, 8, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setGeometry(QtCore.QRect(0, 10, 751, 541))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(210, 20, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = PlotWidget(self.frame_7)
        self.graphicsView.setGeometry(QtCore.QRect(350, 60, 350, 365))
        self.graphicsView.setObjectName("graphicsView")
        self.boton_pdf = QtWidgets.QPushButton(self.frame_7)
        self.boton_pdf.setGeometry(QtCore.QRect(610, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boton_pdf.setFont(font)
        self.boton_pdf.setStyleSheet("background-color: rgb(232, 231, 226);")
        self.boton_pdf.setObjectName("boton_pdf")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana Principal"))
        self.label_opcion.setText(_translate("MainWindow", "Elegir una opción:"))
        self.checkBox_grandes.setText(_translate("MainWindow", "Compras más grandes realizadas en el 2016"))
        self.checkBox_mes.setText(_translate("MainWindow", "Compras más grandes por mes en el 2016"))
        self.checkBox_USAC.setText(_translate("MainWindow", "Compras más grandes realizadas por la Universidad de San Carlos en el 2016"))
        self.checkBox_proveedores.setText(_translate("MainWindow", "Proveedores que más vendieron en 2016"))
        self.boton_visualizar.setText(_translate("MainWindow", "Visualizar"))
        self.label_agregar.setText(_translate("MainWindow", "Agregar compra:"))
        self.label_modalidad.setText(_translate("MainWindow", "Modalidad:"))
        self.comboBox_padre.setItemText(0, _translate("MainWindow", "Sector Público"))
        self.comboBox_padre.setItemText(1, _translate("MainWindow", "Fideicomisos y otras entidades"))
        self.comboBox_padre.setItemText(2, _translate("MainWindow", "Organizaciones Internacionales"))
        self.label_compradora.setText(_translate("MainWindow", "Entidad Compradora:"))
        self.label_entidad.setText(_translate("MainWindow", "Tipo de entidad:"))
        self.label_nit.setText(_translate("MainWindow", "NIT:"))
        self.label_nog.setText(_translate("MainWindow", "NOG concurso:"))
        self.label_adjudicacion.setText(_translate("MainWindow", "Fecha de adjudicación:"))
        self.label_publicacion.setText(_translate("MainWindow", "Fecha de publicación:"))
        self.label_monto.setText(_translate("MainWindow", "Monto:"))
        self.label_padre.setText(_translate("MainWindow", "Tipo de entidad padre:"))
        self.boton_actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Compras 2016"))
        self.label_opcion_2.setText(_translate("MainWindow", "Elegir una opción:"))
        self.checkBox_grandes_2.setText(_translate("MainWindow", "Compras más grandes realizadas en el 2017"))
        self.checkBox_mes_2.setText(_translate("MainWindow", "Compras más grandes por mes en el 2017"))
        self.checkBox_USAC_2.setText(_translate("MainWindow", "Compras más grandes realizadas por la Universidad de San Carlos en el 2017"))
        self.checkBox_proveedores_2.setText(_translate("MainWindow", "Proveedores que más vendieron en 2017"))
        self.boton_visualizar_2.setText(_translate("MainWindow", "Visualizar"))
        self.label_agregar_2.setText(_translate("MainWindow", "Agregar compra:"))
        self.boton_actualizar_2.setText(_translate("MainWindow", "Actualizar"))
        self.label_modalidad_2.setText(_translate("MainWindow", "Modalidad:"))
        self.comboBox_padre_2.setItemText(0, _translate("MainWindow", "Sector Público"))
        self.comboBox_padre_2.setItemText(1, _translate("MainWindow", "Fideicomisos y otras entidades"))
        self.comboBox_padre_2.setItemText(2, _translate("MainWindow", "Organizaciones Internacionales"))
        self.label_compradora_2.setText(_translate("MainWindow", "Entidad Compradora:"))
        self.label_entidad_2.setText(_translate("MainWindow", "Tipo de entidad:"))
        self.label_nit_2.setText(_translate("MainWindow", "NIT:"))
        self.label_nog_2.setText(_translate("MainWindow", "NOG concurso:"))
        self.label_adjudicacion_2.setText(_translate("MainWindow", "Fecha de adjudicación:"))
        self.label_publicacion_2.setText(_translate("MainWindow", "Fecha de publicación:"))
        self.label_monto_2.setText(_translate("MainWindow", "Monto:"))
        self.label_padre_2.setText(_translate("MainWindow", "Tipo de entidad padre:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Compras 2017"))
        self.label_opcion_4.setText(_translate("MainWindow", "Elegir una opción:"))
        self.checkBox_grandes_4.setText(_translate("MainWindow", "Compras más grandes realizadas hasta octubre 2018"))
        self.checkBox_mes_4.setText(_translate("MainWindow", "Compras más grandes por mes hasta octubre 2018"))
        self.checkBox_USAC_4.setText(_translate("MainWindow", "Compras más grandes realizadas por la Universidad de San Carlos hasta octubre 2018"))
        self.checkBox_proveedores_3.setText(_translate("MainWindow", "Proveedores que más vendieron hasta octubre 2018"))
        self.boton_visualizar_4.setText(_translate("MainWindow", "Visualizar"))
        self.label_agregar_4.setText(_translate("MainWindow", "Agregar compra:"))
        self.boton_actualizar_4.setText(_translate("MainWindow", "Actualizar"))
        self.label_modalidad_3.setText(_translate("MainWindow", "Modalidad:"))
        self.comboBox_padre_3.setItemText(0, _translate("MainWindow", "Sector Público"))
        self.comboBox_padre_3.setItemText(1, _translate("MainWindow", "Fideicomisos y otras entidades"))
        self.comboBox_padre_3.setItemText(2, _translate("MainWindow", "Organizaciones Internacionales"))
        self.label_compradora_3.setText(_translate("MainWindow", "Entidad Compradora:"))
        self.label_entidad_3.setText(_translate("MainWindow", "Tipo de entidad:"))
        self.label_nit_3.setText(_translate("MainWindow", "NIT:"))
        self.label_nog_3.setText(_translate("MainWindow", "NOG concurso:"))
        self.label_adjudicacion_3.setText(_translate("MainWindow", "Fecha de adjudicación:"))
        self.label_publicacion_3.setText(_translate("MainWindow", "Fecha de publicación:"))
        self.label_monto_3.setText(_translate("MainWindow", "Monto:"))
        self.label_padre_3.setText(_translate("MainWindow", "Tipo de entidad padre:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Compras 2018"))
        self.label.setText(_translate("MainWindow", "Compras más grandes realizadas en el 2016"))
        self.boton_pdf.setText(_translate("MainWindow", "Generar PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Análisis y gráficas"))

from pyqtgraph import PlotWidget
